modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="lethal_company_boombox_musics"
version="1.1.0"
displayName="Lethal Company Boombox musics"
displayURL="https://modrinth.com/project/lethal-company-boombox-musics"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Zac0511"
description="A mod that allows you to have the Lethal Company boombox in Minecraft"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.lethal_company_boombox_musics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration